name: Go

on:
  workflow_dispatch:
    inputs:
      amf_patch:
        description: 'NF patch'
        required: false
        type: string
      ausf_patch:
        description: 'NF patch'
        required: false
        type: string
      n3iwf_patch:
        description: 'NF patch'
        required: false
        type: string
      nrf_patch:
        description: 'NF patch'
        required: false
        type: string
      nssf_patch:
        description: 'NF patch'
        required: false
        type: string
      pcf_patch:
        description: 'NF patch'
        required: false
        type: string
      smf_patch:
        description: 'NF patch'
        required: false
        type: string
      udm_patch:
        description: 'NF patch'
        required: false
        type: string
      udr_patch:
        description: 'NF patch'
        required: false
        type: string
      upf_patch:
        description: 'NF patch'
        required: false
        type: string
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test with input
      run: |
        echo "PATCH: $UPF_PATCH"
      env:
        UPF_PATCH: ${{ inputs.upf_patch }}
